services:
  db:
    image: mysql:8.4-oraclelinux9
    volumes:
      - ./init/conf:/etc/mysql/conf.d
      - ./init/sql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
volumes:
  db_data: